#thymeleaf 清楚缓存
spring:
  thymeleaf:
    cache: false

  #国际化默认
  messages:
    basename: i18n.login
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss


# 数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/kuang?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver



# 整合mybatis
mybatis:
  type-aliases-package: com.xu.pojo
  mapper-locations: mybatis/mapper/*.xml

